#' create meta study
#'
#' @param foder_path Path of foder where to save `meta_study.txt`.
#' @param type_of_cancer The cancer type abbreviation, e.g., "brca". This should be the same cancer type as specified in the meta_cancer_type.txt file, if available. The type can be "mixed" for studies with multiple cancer types. Check href{https://gdc.cancer.gov/resources-tcga-users/tcga-code-tables/tcga-study-abbreviations}{link} for list of available.
#' @param cancer_study_identifier A string used to uniquely identify this cancer study within the database, e.g., "brca_joneslab_2013".
#' @param name The name of the cancer study, e.g., "Breast Cancer (Jones Lab 2013)".
#' @param description A description of the cancer study, e.g., "Comprehensive profiling of 103 breast cancer samples. Generated by the Jones Lab 2013". This description may contain one or more URLs to relevant information.
#' @param citation A relevant citation, e.g., "TCGA, Nature 2012".
#' @param pmid One or more relevant pubmed ids (comma separated without whitespace). If used, the field citation has to be filled, too.
#' @param groups When using an authenticating cBioPortal, lists the user-groups that are allowed access to this study. Multiple groups are separated with a semicolon ";". The study will be invisible to users not in at least one of the listed groups, as if it wasn't loaded at all. e.g., "PUBLIC;GDAC;SU2C-PI3K". see User-Authorization for more information on groups.
#' @param add_global_case_list set to 'true' if you would like the "All samples" case list to be generated automatically for you. See also Case lists.
#' @param tags_file The file name containing custom study tags for the study tags.
#' @param reference_genome The study reference genome (e.g. hg19, hg38). Without specifying this property, the study will be assigned to the reference genome specified in portal.properties (property ucsc.build).
#' @seealso https://docs.cbioportal.org/file-formats/#cancer-study
#' @return Write a tab delimited file in `folder_path` and return a `data.frame`.
#' @export
create_meta_study <- function(
                              foder_path = getwd(),
                              type_of_cancer,
                              cancer_study_identifier,
                              name,
                              description,
                              citation,
                              pmid,
                              groups,
                              add_global_case_list = "false",
                              tags_file,
                              reference_genome
                              ) {

  passed <- names(as.list(match.call())[-1])
  passed <-  passed[!passed %in%  "foder_path"]
  required_arg <- c("type_of_cancer", "cancer_study_identifier", "name")
  required_arg_missing <- required_arg[!required_arg %in% passed]

  if(length(required_arg_missing) != 0 ) cli::cli_abort("The argument {.field {required_arg_missing}} are required.")

  arg_val <- unlist(lapply(passed, function(x) get(x)))
  out   <- paste(passed, arg_val, sep = ": ")

  file_path <- fs::path(foder_path, "meta_study.txt")
  write.table(out, file = file_path, quote = FALSE, row.names = FALSE, col.names = FALSE, sep = "\t")
  out
}
