#' create meta study
#'
#' @param folder_path Path of folder where to save `meta_study.txt`.
#' @param type_of_cancer The cancer type abbreviation, e.g., "brca". This should be the same cancer type as specified in the meta_cancer_type.txt file, if available. The type can be "mixed" for studies with multiple cancer types. Check href{https://gdc.cancer.gov/resources-tcga-users/tcga-code-tables/tcga-study-abbreviations}{link} for list of available.
#' @param cancer_study_identifier A string used to uniquely identify this cancer study within the database, e.g., "brca_joneslab_2013".
#' @param name The name of the cancer study, e.g., "Breast Cancer (Jones Lab 2013)".
#' @param description A description of the cancer study, e.g., "Comprehensive profiling of 103 breast cancer samples. Generated by the Jones Lab 2013". This description may contain one or more URLs to relevant information.
#' @param citation A relevant citation, e.g., "TCGA, Nature 2012".
#' @param pmid One or more relevant pubmed ids (comma separated without whitespace). If used, the field citation has to be filled, too.
#' @param groups When using an authenticating cBioPortal, lists the user-groups that are allowed access to this study. Multiple groups are separated with a semicolon ";". The study will be invisible to users not in at least one of the listed groups, as if it wasn't loaded at all. e.g., "PUBLIC;GDAC;SU2C-PI3K". see User-Authorization for more information on groups.
#' @param add_global_case_list set to 'true' if you would like the "All samples" case list to be generated automatically for you. See also Case lists.
#' @param tags_file The file name containing custom study tags for the study tags.
#' @param reference_genome The study reference genome (e.g. hg19, hg38). Without specifying this property, the study will be assigned to the reference genome specified in portal.properties (property ucsc.build).
#' @seealso https://docs.cbioportal.org/file-formats/#cancer-study
#' @return Write a tab delimited file in `folder_path` and returns a `data.frame`.
#' @export
create_meta_study <- function(folder_path = getwd(),
                              type_of_cancer,
                              cancer_study_identifier,
                              name,
                              description,
                              citation,
                              pmid,
                              groups,
                              add_global_case_list = "false",
                              tags_file,
                              reference_genome) {
  passed <- names(as.list(match.call())[-1])
  passed <- passed[!passed %in% "folder_path"]
  required_arg <- c("type_of_cancer", "cancer_study_identifier", "name")
  required_arg_missing <- required_arg[!required_arg %in% passed]

  if (length(required_arg_missing) != 0) cli::cli_abort("The argument {.field {required_arg_missing}} are required.")

  arg_val <- unlist(lapply(passed, function(x) get(x)))
  out <- paste(passed, arg_val, sep = ": ")

  file_path <- fs::path(folder_path, "meta_study.txt")
  write.table(out, file = file_path, quote = FALSE, row.names = FALSE, col.names = FALSE, sep = "\t")
  out
}


#' create cancer type
#'
#' cBioPortal Doc indicates that "If the type_of_cancer specified in the `meta_study.txt` does not yet exist in the type_of_cancer database table,
#' a meta_cancer_type.txt file is also mandatory." The function creates the meta file `meta_cancer_type.txt` and the data file associated with it `cancer_type.txt`.
#'
#' @param folder_path Path of folder where to save files.
#' @param type_of_cancer The cancer type abbreviation, e.g., "brca".
#' @param name  The name of the cancer type, e.g., "Breast Invasive Carcinoma".
#' @param dedicated_color CSS color name of the color associated with this cancer study, e.g., "HotPink". See this href{https://www.w3.org/TR/css-color-3/#svg-color}{list}for supported names,
#'    and follow the href{https://en.wikipedia.org/wiki/List_of_awareness_ribbons}{awareness ribbons} color schema. This color is associated with the cancer study on various web pages within
#'    the cBioPortal.
#' @param parent_type_of_cancer The type_of_cancer field of the cancer type of which this is a subtype, e.g., "Breast". ℹ️ : you can set parent to tissue, which is the reserved word to place the
#'    given cancer type at "root" level in the "studies oncotree" that will be generated in the homepage (aka query page) of the portal.
#' @seealso https://docs.cbioportal.org/file-formats/#cancer-study
#' @return Write 2 tab delimited file in `folder_path`.
#' @export
create_cancer_type <- function(
    folder_path = getwd(),
    type_of_cancer,
    name,
    dedicated_color,
    parent_type_of_cancer) {
  passed <- names(as.list(match.call())[-1])
  passed <- passed[!passed %in% "folder_path"]
  required_arg <- c("type_of_cancer", "name", "dedicated_color", "parent_type_of_cancer")
  required_arg_missing <- required_arg[!required_arg %in% passed]

  if (length(required_arg_missing) != 0) cli::cli_abort("The argument {.field {required_arg_missing}} are required.")

  file_path_meta <- fs::path(folder_path, "meta_cancer_type.txt")
  cat("genetic_alteration_type: CANCER_TYPE\ndatatype: CANCER_TYPE\ndata_filename: cancer_type.txt", file = file_path_meta)

  cli::cli_alert("File {.file {file_path_meta}} written.")


  dat <- unlist(lapply(required_arg, function(x) get(x)))

  file_path_cancer_type <- file_path_meta <- fs::path(folder_path, "cancer_type.txt")
  write(dat, file = file_path_cancer_type, sep = "\t", ncolumns = length(dat))
  cli::cli_alert("File {.file {file_path_cancer_type}} written.")
}


#' create meta clinical files
#'
#' Create metaclinical files `meta_clinical_sample.txt` or `meta_clinical_patient.txt` and relative data files `data_clinical_patient.txt` or
#'  `data_clinical_sample.txt`
#'
#' @param folder_path Path of folder where to save files.
#' @param cancer_study_identifier Same value specified in `meta_study.txt`.
#' @param genetic_alteration_type CLINICAL.
#' @param datatype one of `PATIENT_ATTRIBUTES` or `SAMPLE_ATTRIBUTES`.
#' @param clinical_meta A dataframe with a column `var_int` containing `colnames(clinical_dat)`, a column `description` with description of variable.
#' @param clinical_dat A dataframe with first column `PATIENT_ID` or `SAMPLE_ID` and other columns of interest.
#' .  and a column `datatype` with values `STRING`, `NUMBER` or `BOOLEAN`, a numeric column called `attr_priority` and a an upper case name ot the attribute
#' .  in column `attr_name`.
#' @seealso https://docs.cbioportal.org/file-formats/#cancer-study
#' @return Write 2 tab delimited file in `folder_path`.
#' @export
create_meta_clinical <- function(
    folder_path = getwd(),
    genetic_alteration_type = "CLINICAL",
    cancer_study_identifier,
    datatype,
    clinical_dat,
    clinical_meta) {
  passed <- names(as.list(match.call())[-1])
  passed <- passed[!passed %in% "folder_path"]
  required_arg <- c("cancer_study_identifier", "clinical_meta", "datatype")
  required_arg_missing <- required_arg[!required_arg %in% passed]

  if (length(required_arg_missing) != 0) cli::cli_abort("The argument {.field {required_arg_missing}} are required.")

  expected_datatype <- c("PATIENT_ATTRIBUTES", "SAMPLE_ATTRIBUTES")

  if (!datatype %in% expected_datatype) {
    cli::cli_abort("The argument datatype needs to be one of {.field {expected_datatype}}.")
  }

  check_meta_clinical(clinical_dat = clinical_dat, clinical_meta =  clinical_meta, datatype = datatype)

  if (datatype == "PATIENT_ATTRIBUTES") {
    meta_data_filename <- "meta_clinical_patient.txt"
    data_filename <- "data_clinical_patient.txt"
  } else {
    meta_data_filename <- "meta_clinical_sample.txt"
    data_filename <- "data_clinical_sample.txt"
  }

  # Create metaclinical sample or metaclinical patient
  cat("cancer_study_identifier: ",
    cancer_study_identifier, "\n",
    "genetic_alteration_type: ", "CLINICAL", "\n",
    "datatype:  ", datatype, "\n",
    "data_filename: ", data_filename, "\n",
    file = fs::path(folder_path, meta_data_filename), sep = ""
  )

  cli::cli_alert("The file {.file {meta_data_filename}} has been generated.")

  clinical_dat <- clinical_dat[,  clinical_meta$attr_name]
  clinical_meta_t <- as.data.frame(t(clinical_meta))
  clinical_meta_t$V1 <- paste0("#", clinical_meta_t$V1)
  names(clinical_meta_t)  <-  clinical_meta_t[1,]

  clinical_meta_t <- clinical_meta_t[-1, ]

  # Reorder columns

  names(clinical_dat) <- names(clinical_meta_t)
  full_clinical_tab <- rbind(clinical_meta_t, clinical_dat)


  write.table(full_clinical_tab, file = fs::path(folder_path, data_filename), sep = "\t", row.names = FALSE, quote = FALSE)
  cli::cli_alert("The file {.file {data_filename}} has been generated.")
}


#' check meta clinical
#'
#' Verify  dataframes used for `create_meta_clinical`
#'
#' @param clinical_dat
#' @param clinical_meta
#' @param datatype One of `PATIENT_ATTRIBUTES` or `SAMPLE_ATTRIBUTES`.
#'
#' @return stop if requirement are not met
#' @export
check_meta_clinical <- function(clinical_dat, clinical_meta, datatype) {
  if (!setequal(names(clinical_dat), clinical_meta$attr_name)) {
    cli::cli_abort("The columns of clinical_dat are not present in clinical_meta$attr_name.")
  }

  if (datatype == "SAMPLE_ATTRIBUTES") {
    check_attr <- !any(c("SAMPLE_ID", "PATIENT_ID") %in% clinical_meta$attr_name)
  } else {
    check_attr <- !"PATIENT_ID" %in% clinical_meta$attr_name
  }

  if (check_attr) cli::cli_abort("`SAMPLE_ or PATIENT_ID` column missing in clinical_meta")


  if (!all(names(clinical_meta) %in% c("var_int", "description", "datatype", "attr_priority", "attr_name"))) {
    cli::cli_abort("datatype doesn't contain columns `var_int`, `description`, `datatype`. `attr_priority`, `attr_name`")
  }

  if (!all(clinical_meta$datatype %in% c("STRING", "NUMBER", "BOOLEAN"))) {
    cli::cli_abort("Values of datatype$datatype need to be one of STRING, NUMBER OF BOLLEAN.")
  }

  cli::cli_alert("Integrity of data checked.")
}
