#' create meta study
#'
#' @param folder_path Path of folder where to save `meta_study.txt`.
#' @param type_of_cancer The cancer type abbreviation, e.g., "brca". This should be the same cancer type as specified in the meta_cancer_type.txt file, if available. The type can be "mixed" for studies with multiple cancer types. Check href{https://gdc.cancer.gov/resources-tcga-users/tcga-code-tables/tcga-study-abbreviations}{link} for list of available.
#' @param cancer_study_identifier A string used to uniquely identify this cancer study within the database, e.g., "brca_joneslab_2013".
#' @param name The name of the cancer study, e.g., "Breast Cancer (Jones Lab 2013)".
#' @param description A description of the cancer study, e.g., "Comprehensive profiling of 103 breast cancer samples. Generated by the Jones Lab 2013". This description may contain one or more URLs to relevant information.
#' @param citation A relevant citation, e.g., "TCGA, Nature 2012".
#' @param pmid One or more relevant pubmed ids (comma separated without whitespace). If used, the field citation has to be filled, too.
#' @param groups When using an authenticating cBioPortal, lists the user-groups that are allowed access to this study. Multiple groups are separated with a semicolon ";". The study will be invisible to users not in at least one of the listed groups, as if it wasn't loaded at all. e.g., "PUBLIC;GDAC;SU2C-PI3K". see User-Authorization for more information on groups.
#' @param add_global_case_list set to 'true' if you would like the "All samples" case list to be generated automatically for you. See also Case lists.
#' @param tags_file The file name containing custom study tags for the study tags.
#' @param reference_genome The study reference genome (e.g. hg19, hg38).
#'   Without specifying this property, the study will be assigned to the reference genome specified in portal.properties (property ucsc.build).
#' @seealso \url{https://docs.cbioportal.org/file-formats/#cancer-study}
#' @return Write a tab delimited file in `folder_path`.
#' @export
create_meta_study <- function(folder_path,
                              type_of_cancer,
                              cancer_study_identifier,
                              name,
                              description,
                              citation,
                              pmid,
                              groups,
                              add_global_case_list = "false",
                              tags_file,
                              reference_genome) {
  required_arg <- c("type_of_cancer", "cancer_study_identifier", "name", "folder_path")
  all_args <- handler::handle_required_args(required_arg = required_arg, get_arg = TRUE)

  all_args <- all_args[names(all_args) != "folder_path"]

  out <- paste(names(all_args), all_args, sep = ": ")

  file_path <- fs::path(folder_path, "meta_study.txt")
  utils::write.table(out, file = file_path, quote = FALSE, row.names = FALSE, col.names = FALSE, sep = "\t")
  cli::cli_alert("File {.file {file_path}} written.")
}


#' create cancer type
#'
#' cBioPortal Doc indicates that "If the type_of_cancer specified in the `meta_study.txt` does not yet exist in the type_of_cancer database table,
#' a meta_cancer_type.txt file is also mandatory." The function creates the meta file `meta_cancer_type.txt` and the data file associated with it `cancer_type.txt`.
#'
#' @param folder_path Path of folder where to save files.
#' @param type_of_cancer The cancer type abbreviation, e.g., "brca".
#' @param name  The name of the cancer type, e.g., "Breast Invasive Carcinoma".
#' @param dedicated_color CSS color name of the color associated with this cancer study, e.g., "HotPink". See this href{https://www.w3.org/TR/css-color-3/#svg-color}{list}for supported names,
#'    and follow the href{https://en.wikipedia.org/wiki/List_of_awareness_ribbons}{awareness ribbons} color schema. This color is associated with the cancer study on various web pages within
#'    the cBioPortal.
#' @param parent_type_of_cancer The type_of_cancer field of the cancer type of which this is a subtype, e.g., "Breast". ℹ️ : you can set parent to tissue, which is the reserved word to place the
#'    given cancer type at "root" level in the "studies oncotree" that will be generated in the homepage (aka query page) of the portal.
#' @seealso \url{https://docs.cbioportal.org/file-formats/#cancer-study}
#' @return Write 2 tab delimited files in `folder_path`.
#' @export
create_cancer_type <- function(
    folder_path,
    type_of_cancer,
    name,
    dedicated_color,
    parent_type_of_cancer) {
  required_arg <- c("type_of_cancer", "name", "dedicated_color", "parent_type_of_cancer", "folder_path")
  all_args <- handler::handle_required_args(required_arg = required_arg, get_arg = TRUE)

  all_args <- all_args[!names(all_args) %in% "folder_path"]

  file_path_meta <- fs::path(folder_path, "meta_cancer_type.txt")
  cat("genetic_alteration_type: CANCER_TYPE\ndatatype: CANCER_TYPE\ndata_filename: cancer_type.txt\n", file = file_path_meta)

  cli::cli_alert("File {.file {file_path_meta}} written.")


  out <- paste(names(all_args), all_args, sep = ": ")

  file_path_cancer_type <- fs::path(folder_path, "cancer_type.txt")
  write(out, file = file_path_cancer_type, sep = "\t", ncolumns = 1)
  cli::cli_alert("File {.file {file_path_cancer_type}} written.")
}


#' create clinical files
#'
#' Create clinical files `meta_clinical_sample.txt` or `meta_clinical_patient.txt` and relative data files `data_clinical_patient.txt` or
#'  `data_clinical_sample.txt`
#'
#' @param folder_path Path of folder where to save files.
#' @param cancer_study_identifier Same value specified in `meta_study.txt`.
#' @param genetic_alteration_type CLINICAL.
#' @param datatype one of `PATIENT_ATTRIBUTES` or `SAMPLE_ATTRIBUTES`.
#' @param clinical_meta A dataframe with a column `var_int` containing `colnames(clinical_dat)`, a column `description` with description of variable.
#' @param clinical_dat A dataframe with first column `PATIENT_ID` or `SAMPLE_ID` and other columns of interest.
#' .  and a column `datatype` with values `STRING`, `NUMBER` or `BOOLEAN`, a numeric column called `attr_priority` and a an upper case name ot the attribute
#' .  in column `attr_name`.
#' @details
#' See Note on survival plots in https://docs.cbioportal.org/file-formats/#cancer-study for additional details on
#' survival plots.
#' @seealso \url{https://docs.cbioportal.org/file-formats/#clinical-data}
#' @return Write 2 tab delimited files in `folder_path`.
#' @export
create_clinical <- function(
    folder_path,
    genetic_alteration_type = "CLINICAL",
    cancer_study_identifier,
    datatype,
    clinical_dat,
    clinical_meta) {

  required_arg <- c("cancer_study_identifier", "clinical_meta", "datatype", "folder_path")
  handler::handle_required_args(
    required_arg = required_arg,
    get_arg = FALSE
  )


  check_clinical(clinical_dat = clinical_dat, clinical_meta = clinical_meta, datatype = datatype)

  if (datatype == "PATIENT_ATTRIBUTES") {
    meta_data_filename <- "meta_clinical_patient.txt"
    data_filename <- "data_clinical_patient.txt"
  } else {
    meta_data_filename <- "meta_clinical_sample.txt"
    data_filename <- "data_clinical_sample.txt"
  }

  path_meta_data_filename <- fs::path(folder_path, meta_data_filename)
  # Create metaclinical sample or metaclinical patient
  cat("cancer_study_identifier: ",
    cancer_study_identifier, "\n",
    "genetic_alteration_type: ", "CLINICAL", "\n",
    "datatype:  ", datatype, "\n",
    "data_filename: ", data_filename, "\n",
    file = path_meta_data_filename, sep = ""
  )

  cli::cli_alert("The file {.file {path_meta_data_filename}} has been generated.")

  # Reorder columns
  clinical_dat <- clinical_dat[, clinical_meta$attr_name]
  clinical_meta_t <- as.data.frame(t(clinical_meta))
  clinical_meta_t$V1 <- paste0("#", clinical_meta_t$V1)


  # take header from first column and remove it
  names(clinical_meta_t) <- clinical_meta_t[1, ]
  clinical_meta_t <- clinical_meta_t[-1, ]


  names(clinical_dat) <- names(clinical_meta_t)
  full_clinical_tab <- rbind(clinical_meta_t, clinical_dat)

  path_data_file_name <- fs::path(folder_path, data_filename)
  utils::write.table(full_clinical_tab, file = path_data_file_name, sep = "\t", row.names = FALSE, quote = FALSE)
  cli::cli_alert("The file {.file {path_data_file_name}} has been generated.")
}

#' create expression files
#'
#' Create expression files `meta_clinical_sample.txt` and relative data files `data_expression.txt`.
#'
#' @param folder_path Path of folder where to save files.
#' @param cancer_study_identifier Same value specified in `meta_study.txt`.
#' @param genetic_alteration_type MRNA_EXPRESSION.
#' @param datatype one of `CONTINUOUS`, `DISCRETE` or `Z-SCORE`.
#' @param stable_id Check `Supported stable_id values for MRNA_EXPRESSION` in https://docs.cbioportal.org/file-formats/#expression-data.
#' @param source_stable_id Required when both conditions are true: (1) datatype = Z-SCORE and (2)
#' this study contains GSVA data. Should contain stable_id of the expression file for which this Z-SCORE file is the statistic.
#' @param show_profile_in_analysis_tab false (you can set to true if Z-SCORE to enable it in the oncoprint, for example).
#' @param profile_name A name for the expression data, e.g., "mRNA expression (microarray)".
#' @param profile_description A description of the expression data, e.g., "Expression levels (Agilent microarray).".
#' @param expr_matrix  A matrix with expression data.
#' @param gene_id_type Either "hugo" or "entrez".
#' @param gene_panel Optional gene panel stable id.
#' @seealso \url{https://docs.cbioportal.org/file-formats/#expression-data}
#' @return Write 2 tab delimited files in `folder_path`.
#' @export
create_expression <- function(
    folder_path,
    cancer_study_identifier,
    genetic_alteration_type = "MRNA_EXPRESSION",
    datatype,
    stable_id,
    source_stable_id = NULL,
    show_profile_in_analysis_tab = FALSE,
    profile_name,
    profile_description,
    expr_matrix,
    gene_id_type,
    gene_panel = NULL) {

  required_arg <- c(
    "cancer_study_identifier",
    "datatype",
    "stable_id",
    "profile_name",
    "expr_matrix",
    "profile_description",
    "folder_path",
    "gene_id_type"
  )
  all_args <- handler::handle_required_args(required_arg = required_arg, get_arg = TRUE)

  arg_val <- all_args[!unlist(lapply(all_args, is.null))]
  arg_val <- arg_val[!names(arg_val) %in% c("expr_matrix", "folder_path", "gene_id_type")]

  out <- paste(names(arg_val), arg_val, sep = ": ")
  out <- c(out, "data_filename: data_expression.txt")

  file_path <- fs::path(folder_path, "meta_expression.txt")
  utils::write.table(out, file = file_path, quote = FALSE, row.names = FALSE, col.names = FALSE, sep = "\t")
  cli::cli_alert("The file {.file {file_path}} has been generated.")


  check_expr(expr_matrix)
  if (!gene_id_type %in% c("hugo", "entrez")) cli::cli_abort("The {field gene_id_type} needs to be either 'hugo' or 'entrez")


  expr_df <- data.frame(expr_matrix)
  expr_df[, "gene"] <- row.names(expr_df)
  new_order <- c("gene", names(expr_df)[!names(expr_df) %in% "gene"])
  expr_df_r <- expr_df[, new_order]
  if (gene_id_type == "hugo") {
    names(expr_df_r)[1] <- "Hugo_Symbol"
  } else {
    names(expr_df_r)[1] <- "Entrez_Gene_Id"
  }

  file_path_data <- fs::path(folder_path, "data_expression.txt")
  utils::write.table(expr_df_r, file = file_path_data, quote = FALSE, row.names = FALSE, col.names = TRUE, sep = "\t")
  cli::cli_alert("The file {.file {file_path_data}} has been generated.")
}
